name       : haskell-cabal-install
version    : 1.24.0.0
release    : 1
source     :
    - https://github.com/haskell/cabal/archive/Cabal-v1.24.0.0.tar.gz : f0c9ee7063ce896f31067c711e6a13a210df6b217999812b365f6f0e15b55a10
license    : BSD-3-Clause
component  : programming
summary    : cabal-install is a library management tool for the Haskell Language
description: |
    cabal-install is a library management tool for the Haskell Language
builddeps  :
    - ghc
    - haskell-async
    - haskell-base16-bytestring
    - haskell-cryptohash-sha256
    - haskell-hackage-security
    - haskell-hashable
    - haskell-HTTP
    - haskell-mtl
    - haskell-network
    - haskell-network-uri
    - haskell-random
    - haskell-stm
    - haskell-tar
    - haskell-zlib
setup      : |
    sudo ghc-pkg recache
    cd cabal-install
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --datadir=/usr/share \
                      --sysconfdir=/etc \
                      --libexecdir=/usr/lib64/cabal \
                      --libsubdir="\$compiler/\$pkgid"
build      : |
    cd cabal-install
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    cd cabal-install
    ./Setup copy --destdir=$installdir
