name       : haskell-cabal-install
version    : 3.6.2.0
release    : 9
source     :
    # Revision 2
    - https://hackage.haskell.org/package/cabal-install-3.6.2.0/cabal-install-3.6.2.0.tar.gz : dcf99e1d5f1c6e569e7386312fe96e9804b3cfb2d4f17ded1e01f60149bd3036
license    : BSD-3-Clause
component  : programming.haskell
summary    : cabal-install is a library management tool for the Haskell Language
description: |
    cabal-install is a library management tool for the Haskell Language
builddeps  :
    - ghc-devel
    - haskell-async-devel
    - haskell-base16-bytestring-devel
    - haskell-cryptohash-sha256-devel
    - haskell-echo-devel
    - haskell-edit-distance-devel
    - haskell-hackage-security-devel
    - haskell-hashable-devel
    - haskell-http-devel
    - haskell-lukko-devel
    - haskell-network-uri-devel
    - haskell-random-devel
    - haskell-regex-base-devel
    - haskell-regex-posix-devel
    - haskell-tar-devel
    - haskell-resolv-devel
    - haskell-zlib-devel
rundeps    :
    - ghc-devel
    - haskell-async-devel
    - haskell-base16-bytestring-devel
    - haskell-cryptohash-sha256-devel
    - haskell-echo-devel
    - haskell-edit-distance-devel
    - haskell-hackage-security-devel
    - haskell-hashable-devel
    - haskell-http-devel
    - haskell-lukko-devel
    - haskell-network-uri-devel
    - haskell-random-devel
    - haskell-regex-base-devel
    - haskell-regex-posix-devel
    - haskell-tar-devel
    - haskell-resolv-devel
    - haskell-zlib-devel
setup      : |
    cp $pkgfiles/2.cabal cabal-install.cabal
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
