name       : haskell-cabal-install
version    : 1.24.0.0
release    : 2
source     :
    - https://github.com/haskell/cabal/archive/Cabal-v1.24.0.0.tar.gz : f0c9ee7063ce896f31067c711e6a13a210df6b217999812b365f6f0e15b55a10
license    : BSD-3-Clause
component  : programming.haskell
summary    : cabal-install is a library management tool for the Haskell Language
description: |
    cabal-install is a library management tool for the Haskell Language
builddeps  :
    - ghc-devel
    - haskell-async
    - haskell-base16-bytestring
    - haskell-cabal-install
    - haskell-cryptohash-sha256
    - haskell-hackage-security
    - haskell-hashable
    - haskell-HTTP
    - haskell-mtl
    - haskell-network
    - haskell-network-uri
    - haskell-random
    - haskell-stm
    - haskell-tar
    - haskell-zlib
setup      : |
    cd cabal-install
    %cabal_configure
build      : |
    cd cabal-install
    %cabal_build
install    : |
    cd cabal-install
    %cabal_install
